/* Humour Me's phrases. Originals: Cards Against Humanity's text is licensed
 * for non-commercial use only. The server deals one per room by index
 * (`room.content`), so this list ships only with the Humour Me module and
 * the API, never with the party page. Each has exactly one blank, "___". */
export const PROMPTS = [
  "The real reason I'm late is ___.",
  "My toxic trait is thinking I can ___.",
  "Breaking news: local man arrested for ___ at a wedding.",
  "New startup idea: Uber, but for ___.",
  "What my mom thinks I do at parties: ___.",
  "Nobody warned me adulthood is mostly ___.",
  "The real reason the Wi-Fi password is so long: ___.",
  "___: the only thing keeping this party alive.",
  "The worst name for a dating app: ___.",
  "My autobiography would be called ___.",
  "The group chat went silent after someone sent ___.",
  "My last brain cell is busy thinking about ___.",
  "The secret ingredient in my cooking is ___.",
  "I'd survive a zombie apocalypse thanks to ___.",
  "The most useless superpower: ___.",
  "My landlord's new rule: no ___.",
  "Tonight's dinner is ___, and nobody is happy about it.",
  "The terms and conditions secretly say ___.",
  "My horoscope says this week I should avoid ___.",
  "I got banned from the gym for ___.",
  "The best excuse to leave a party early: ___.",
  "Scientists finally discovered what cats are thinking: ___.",
  "My most-used emoji is a cry for ___.",
  "The airport security guard found ___ in my bag.",
  "My 2 a.m. search history: ___.",
  "Dad's one rule on road trips: ___.",
  "The aunty at the wedding asked me about ___.",
  "Sharma ji's son just ___.",
  "If my life were a movie, the title would be ___.",
  "The weirdest thing in my fridge right now: ___.",
  "My boss thinks I'm working, but I'm actually ___.",
  "The next big trend on Instagram: ___.",
  "The real reason dinosaurs went extinct: ___.",
  "My villain origin story begins with ___.",
  "The only thing scarier than a ghost: ___.",
  "Rejected flavour of ice cream: ___.",
  "My neighbour keeps knocking to complain about ___.",
  "The shortest job interview ever ended because of ___.",
  "What I'd bring to a deserted island: ___.",
  "The new national holiday celebrates ___.",
  "My phone autocorrects everything to ___.",
  "Inside my bag right now: keys, wallet and ___.",
  "Worst thing to say on a first date: ___.",
  "My personal brand is ___.",
  "The family WhatsApp group is arguing about ___ again.",
  "The cricket match was stopped because of ___.",
  "I knew the party was over when I saw ___.",
  "My retirement plan is ___.",
  "Every school trip had one kid who ___.",
  "The hostel's most famous rule: no ___.",
  "Coming soon to Netflix: a documentary about ___.",
  "The real reason I can't sleep: ___.",
  "My love language is ___.",
  "The wedding DJ only plays ___.",
  "What's really in the office microwave: ___.",
  "I'm not lazy, I'm just ___.",
  "The secret to a long life: ___.",
  "Things you shouldn't say to a pilot: ___.",
  "The next Olympic sport: competitive ___.",
  "My emotional support item is ___.",
];
