/* Humour Me's phrases. Originals: Cards Against Humanity's text is licensed
 * for non-commercial use only. The server deals one per room by index
 * (`room.prompt`), so this list ships only with the Humour Me module and
 * the API, never with the party page. Each has exactly one blank, "___";
 * `{name}` is someone in the round, filled in by phraseFor(). */

import { eligible, stream, timetable } from "../rules.js";

/** The room's phrase, with every `{name}` the same player on every phone:
 *  picked from the room's seed among those in the round. */
export function phraseFor(room) {
  const text = PROMPTS[room.prompt] || PROMPTS[0];
  if (!text.includes("{name}")) return text;
  const who = eligible(room, timetable(room).playAt);
  const name = who.length ? who[Math.floor(stream(room.seed)() * who.length)].name : "Someone";
  // A function, so a name such as "$&" is text and not a replacement pattern.
  return text.replaceAll("{name}", () => name);
}

export const PROMPTS = [
  "The real reason I'm late is ___.",
  "Breaking news: local man arrested for ___ at a wedding.",
  "New startup idea: Uber, but for ___.",
  "What my mom thinks I do at parties: ___.",
  "Nobody warned me adulthood is mostly ___.",
  "The real reason the Wi-Fi password is so long: ___.",
  "___: the only thing keeping this party alive.",
  "The worst name for a dating app: ___.",
  "The group chat went silent after someone sent ___.",
  "The secret ingredient in my cooking is ___.",
  "I'd survive a zombie apocalypse thanks to ___.",
  "The most useless superpower: ___.",
  "My landlord's new rule: no ___.",
  "Tonight's dinner is ___, and nobody is happy about it.",
  "The terms and conditions secretly say ___.",
  "I got banned from the gym for ___.",
  "The best excuse to leave a party early: ___.",
  "Scientists finally discovered what cats are thinking: ___.",
  "The airport security guard found ___ in my bag.",
  "Dad's one rule on road trips: ___.",
  "The aunty at the wedding asked me about ___.",
  "Sharma ji's son just ___.",
  "The weirdest thing in my fridge right now: ___.",
  "The next big trend on Instagram: ___.",
  "The real reason dinosaurs went extinct: ___.",
  "The only thing scarier than a ghost: ___.",
  "Rejected flavour of ice cream: ___.",
  "My neighbour keeps knocking to complain about ___.",
  "The shortest job interview ever ended because of ___.",
  "What I'd bring to a deserted island: ___.",
  "The new national holiday celebrates ___.",
  "Inside my bag right now: keys, wallet and ___.",
  "Worst thing to say on a first date: ___.",
  "The family WhatsApp group is arguing about ___ again.",
  "The cricket match was stopped because of ___.",
  "I knew the party was over when I saw ___.",
  "Every school trip had one kid who ___.",
  "The hostel's most famous rule: no ___.",
  "Coming soon to Netflix: a documentary about ___.",
  "The real reason I can't sleep: ___.",
  "The wedding DJ only plays ___.",
  "What's really in the office microwave: ___.",
  "The secret to a long life: ___.",
  "Things you shouldn't say to a pilot: ___.",
  "The next Olympic sport: competitive ___.",

  // Family, shaadi and sanskar.
  "The rishta fell through when the boy's family found out about ___.",
  "Papa's three topics at every dinner: politics, petrol prices and ___.",
  "What the astrologer says is blocking my marriage: ___.",
  "The NRI cousin's suitcase was full of ___.",
  "Haldi doodh cures everything except ___.",
  "The joint family stopped talking after ___.",
  "Four years of engineering taught me nothing except ___.",
  "Mummy's scariest threat: 'Wait till your father hears about ___.'",
  "Sanskari on the outside, ___ on the inside.",
  "What's actually in Dadi's locked steel almirah: ___.",
  "Diwali cleaning uncovered ___.",
  "The pandit stopped the pheras halfway because of ___.",
  "The matrimonial ad: 'Tall, well settled, and ___.'",

  // Short and stupid.
  "What's that smell? Oh no. It's ___.",
  "___: kid-tested, aunty-approved.",
  "Coming this Friday: ___, the musical.",
  "Shah Rukh opens his arms in the rain, and runs straight into ___.",
  "What is the government hiding? ___.",
  "Why am I sticky? ___.",
  "The cleanest way to end a friendship: ___.",
  "KBC's new lifeline: ___.",
  "This week's Bigg Boss task: ___.",

  // About someone in the room.
  "{name}'s Spotify Wrapped was just ___ on repeat.",
  "In 2040, {name} will be famous for ___.",
  "If we're ever stranded, we eat {name} first because ___.",
  "{name}'s search history, read aloud at their funeral: ___.",
  "The group chat has a secret second group chat, just to discuss {name}'s ___.",
  "{name} is banned from every family function for ___.",
  "{name}'s dating profile says 'looking for ___'.",
  "{name}'s LinkedIn headline: 'Visionary. Leader. ___.'",
  "{name} has never once been on time, because of ___.",
  "{name}'s villain era started with ___.",
  "If {name} ran the country, day one would be ___.",
  "{name}'s therapist's notes just say ___.",
  "{name}'s red flag that we've all just accepted: ___.",
  "The Netflix documentary about {name} is called ___.",
  "{name} would survive a horror movie by ___.",
  "{name}'s mom still tells the relatives that {name} is ___.",
  "{name}'s last words will probably be ___.",
  "What {name} actually does at work all day: ___.",
  "{name} got kicked off the group trip for ___.",
  "{name}'s superpower is ___, and it's useless.",
  "{name} is trending on Twitter for ___.",
  "{name}'s guilty pleasure, revealed at last: ___.",
  "The one thing {name} should never be trusted with: ___.",
  "{name}'s wedding speech will be twenty minutes about ___.",
  "{name} has 47 tabs open, and every one of them is ___.",
  "In school, {name} was voted most likely to ___.",
  "The FBI agent watching {name}'s phone has started ___.",
  "{name} will be the first to die in a zombie movie, because of ___.",
  "{name}'s Uber rating is 3.2 because of ___.",
  "{name}'s parents are still recovering from ___.",
  "Every voice note {name} sends is ten minutes about ___.",
  "{name}'s 'quick question' always turns into ___.",
  "The aunties at the wedding are still talking about {name}'s ___.",

  // The state of things.
  "My therapist and I agreed the real problem is ___.",
  "LinkedIn post: 'I got laid off, and here's what ___ taught me about leadership.'",
  "AI took my job. It also took ___.",
  "The AQI is so bad my lungs have started ___.",
  "The 10-minute delivery app's newest category: ___.",
  "My screen-time report has started calling me ___.",
  "Rent went up again, so now I'm ___.",
  "My will leaves everything to ___.",
  "My funeral playlist opens with ___.",
  "What I'll say to the AI overlords so they spare me: ___.",
  "Every startup pitch now: 'It's like ChatGPT, but for ___.'",
  "Doomscrolling at 3 a.m. taught me ___.",
  "I'll finish paying my EMIs right after ___.",
  "My salary hit my account and immediately left for ___.",
  "The influencer's twelve-minute apology video was about ___.",
  "Instead of a raise, HR gave us ___.",
  "The apocalypse is here, and the first thing to go is ___.",
  "The traffic was so bad that, before the signal turned green, I ___.",
  "My nephew says I'm cringe because of ___.",
  "The new productivity hack everyone swears by: ___.",

  // History, as it really happened.
  "The real reason the Titanic sank: ___.",
  "Napoleon's real insecurity wasn't his height. It was ___.",
  "The eleventh commandment, cut from the final draft: 'Thou shalt not ___.'",
  "Shah Jahan built the Taj Mahal, but his first idea was ___.",
  "Columbus went looking for India and found ___ instead.",
  "The real reason the Roman Empire fell: ___.",
  "Akbar had nine gems in his court. The tenth was fired for ___.",
  "Newton discovered gravity, then immediately discovered ___.",
  "The cave painting historians still can't explain shows ___.",
  "What the pyramids were really built to store: ___.",
  "Cleopatra's skincare routine, finally revealed: ___.",
  "The moon landing was real, but NASA definitely faked ___.",
  "Shakespeare's lost play: Romeo and ___.",
  "Before the wheel, people got around by ___.",
  "The dinosaurs' last group chat message: ___.",
  "The Mona Lisa is smiling because ___.",
  "Einstein's lesser-known theory: ___.",
  "Chanakya's lost rule for kings: never ___.",
  "Ancient Romans cured a hangover with ___.",
  "Archimedes ran naked through the streets shouting 'Eureka!' because he'd found ___.",
];
